package cn.xiandu.app.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import cn.xiandu.app.bean.HomeBean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "HOME_BEAN".
*/
public class HomeBeanDao extends AbstractDao<HomeBean, String> {

    public static final String TABLENAME = "HOME_BEAN";

    /**
     * Properties of entity HomeBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, String.class, "id", true, "ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Source = new Property(2, String.class, "source", false, "SOURCE");
        public final static Property FirstImg = new Property(3, String.class, "firstImg", false, "FIRST_IMG");
        public final static Property Mark = new Property(4, String.class, "mark", false, "MARK");
        public final static Property Url = new Property(5, String.class, "url", false, "URL");
    }


    public HomeBeanDao(DaoConfig config) {
        super(config);
    }
    
    public HomeBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"HOME_BEAN\" (" + //
                "\"ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: id
                "\"TITLE\" TEXT," + // 1: title
                "\"SOURCE\" TEXT," + // 2: source
                "\"FIRST_IMG\" TEXT," + // 3: firstImg
                "\"MARK\" TEXT," + // 4: mark
                "\"URL\" TEXT);"); // 5: url
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"HOME_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, HomeBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(3, source);
        }
 
        String firstImg = entity.getFirstImg();
        if (firstImg != null) {
            stmt.bindString(4, firstImg);
        }
 
        String mark = entity.getMark();
        if (mark != null) {
            stmt.bindString(5, mark);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, HomeBean entity) {
        stmt.clearBindings();
 
        String id = entity.getId();
        if (id != null) {
            stmt.bindString(1, id);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String source = entity.getSource();
        if (source != null) {
            stmt.bindString(3, source);
        }
 
        String firstImg = entity.getFirstImg();
        if (firstImg != null) {
            stmt.bindString(4, firstImg);
        }
 
        String mark = entity.getMark();
        if (mark != null) {
            stmt.bindString(5, mark);
        }
 
        String url = entity.getUrl();
        if (url != null) {
            stmt.bindString(6, url);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public HomeBean readEntity(Cursor cursor, int offset) {
        HomeBean entity = new HomeBean( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // source
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // firstImg
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // mark
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5) // url
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, HomeBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setSource(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setFirstImg(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMark(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUrl(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
     }
    
    @Override
    protected final String updateKeyAfterInsert(HomeBean entity, long rowId) {
        return entity.getId();
    }
    
    @Override
    public String getKey(HomeBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(HomeBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
